"""initial: 15 tables

Revision ID: 11a27794a41e
Revises: 
Create Date: 2026-04-03 07:25:33.478403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect


# revision identifiers, used by Alembic.
revision: str = '11a27794a41e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Guard: skip if tables already exist (created by Base.metadata.create_all on startup).
    conn = op.get_bind()
    if 'alerts' in sa_inspect(conn).get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=True),
    sa.Column('intent_name', sa.String(), nullable=True),
    sa.Column('handler', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('response_preview', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('args_summary', sa.String(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('backtest_results',
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('benchmark_value', sa.Float(), nullable=False),
    sa.Column('allocation', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('backtest_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('strategy_params', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('config_overrides',
    sa.Column('override_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_table('manoeuvres',
    sa.Column('manoeuvre_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('lot_key', sa.String(), nullable=False),
    sa.Column('from_group', sa.String(), nullable=True),
    sa.Column('to_group', sa.String(), nullable=True),
    sa.Column('nifty_spot', sa.Float(), nullable=True),
    sa.Column('banknifty_spot', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('manoeuvre_id')
    )
    op.create_table('market_data_cache',
    sa.Column('cache_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('shares_traded', sa.Integer(), nullable=True),
    sa.Column('turnover_cr', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('model_registry',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('change', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('backtest_sharpe', sa.Float(), nullable=True),
    sa.Column('backtest_mdd', sa.Float(), nullable=True),
    sa.Column('backtest_return', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_filled', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('portfolio',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('view', sa.String(), nullable=True),
    sa.Column('pnl_now', sa.Float(), nullable=False),
    sa.Column('sl_pnl', sa.Float(), nullable=True),
    sa.Column('target_pnl', sa.Float(), nullable=True),
    sa.Column('lot_count', sa.Integer(), nullable=False),
    sa.Column('nifty_spot', sa.Float(), nullable=True),
    sa.Column('banknifty_spot', sa.Float(), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=True),
    sa.Column('pct_from_sl', sa.Float(), nullable=True),
    sa.Column('pct_from_target', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiry', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('last_traded_price', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('risk_timeline',
    sa.Column('risk_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('allocation', sa.Float(), nullable=False),
    sa.Column('portfolio_value_norm', sa.Float(), nullable=False),
    sa.Column('portfolio_value_inr', sa.Float(), nullable=False),
    sa.Column('rolling_vol_20d', sa.Float(), nullable=True),
    sa.Column('market_var_95', sa.Float(), nullable=True),
    sa.Column('portfolio_var_95', sa.Float(), nullable=True),
    sa.Column('portfolio_cvar_95', sa.Float(), nullable=True),
    sa.Column('current_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('drawdown_budget_pct', sa.Float(), nullable=False),
    sa.Column('position_risk_pct', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('inr_at_risk', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('view', sa.String(), nullable=False),
    sa.Column('lot_key', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('pnl_now', sa.Float(), nullable=False),
    sa.Column('pnl_sl', sa.Float(), nullable=False),
    sa.Column('pnl_target', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('trades',
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('expiry', sa.String(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('training_metrics',
    sa.Column('metric_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('epsilon', sa.Float(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('training_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('timesteps', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('buffer_size', sa.Integer(), nullable=False),
    sa.Column('net_arch', sa.String(), nullable=False),
    sa.Column('exploration_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('backtest_sharpe', sa.Float(), nullable=True),
    sa.Column('backtest_mdd', sa.Float(), nullable=True),
    sa.Column('backtest_return', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_runs')
    op.drop_table('training_metrics')
    op.drop_table('trades')
    op.drop_table('snapshots')
    op.drop_table('risk_timeline')
    op.drop_table('positions')
    op.drop_table('portfolio')
    op.drop_table('orders')
    op.drop_table('model_registry')
    op.drop_table('market_data_cache')
    op.drop_table('manoeuvres')
    op.drop_table('config_overrides')
    op.drop_table('backtest_runs')
    op.drop_table('backtest_results')
    op.drop_table('audit_log')
    op.drop_table('alerts')
    # ### end Alembic commands ###
